apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kmr-manager
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - pods/log
    verbs: ["*"]
  - apiGroups:
      - extensions
    resources:
      - replicasets
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kmr-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kmr-manager
subjects:
- kind: ServiceAccount
  name: kmr-manager
  namespace: default
